theme = "dark_plus"

[editor]
mouse = true
undercurl = true
true-color = true
default-line-ending = "lf"
line-number = "relative"
bufferline = "always"

text-width = 100
rulers = [ 100 ]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┊"  # "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-inlay-hints = false

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "→"
nbsp = "⍽"
nnbsp = "⍽"
newline = "⏎"
tabpad = "·"

[keys.normal]
ins = "insert_mode"
esc = [ "collapse_selection", "keep_primary_selection" ]

A-left = ":buffer-previous"
A-right = ":buffer-next"

[keys.insert]
ins = "normal_mode"

A-left = ":buffer-previous"
A-right = ":buffer-next"
